################################################################################
# RuboCop setup
################################################################################
require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'bundix.gemspec'
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
  Exclude:
    - 'vendor/**/*'


################################################################################
# Individual cop configurations
################################################################################
Minitest/MultipleAssertions:
  Max: 5

Naming/FileName:
  Exclude:
    - 'Rakefile'
    - '**/Gemfile'
