################################################################################
# RuboCop setup
################################################################################
require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'bundix.gemspec'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'vendor/**/*'


################################################################################
# Individual cop configurations
################################################################################
Naming/FileName:
  Exclude:
    - 'Rakefile'
    - '**/Gemfile'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'
